name: build.yaml

on:
  push:
    branches:
      - main
  workflow_dispatch:   # Allows manual run

jobs:
  hello-world:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello World from GitHub-hosted runner!"
